import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "reference/openapi/ory-apis",
    },
    {
      type: "category",
      label: "identity",
      items: [
        {
          type: "doc",
          id: "reference/openapi/list-identities",
          label: "List Identities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/batch-patch-identities",
          label: "Create multiple identities",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/create-identity",
          label: "Create an Identity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/get-identity-by-external-id",
          label: "Get an Identity by its External ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-identity",
          label: "Delete an Identity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-identity",
          label: "Get an Identity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/patch-identity",
          label: "Patch an Identity",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/update-identity",
          label: "Update an Identity",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-identity-credentials",
          label: "Delete a credential for a specific identity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-identity-sessions",
          label: "Delete & Invalidate an Identity's Sessions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/list-identity-sessions",
          label: "List an Identity's Sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-recovery-code-for-identity",
          label: "Create a Recovery Code",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-recovery-link-for-identity",
          label: "Create a Recovery Link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/list-sessions",
          label: "List All Sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/manage-sessions",
          label: "Manage sessions in bulk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/disable-session",
          label: "Deactivate a Session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-session",
          label: "Get Session",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/extend-session",
          label: "Extend a Session",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/create-test-login-flow",
          label: "Create a test OIDC login flow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/list-identity-schemas",
          label: "Get all Identity Schemas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-identity-schema",
          label: "Get Identity JSON Schema",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "frontend",
      items: [
        {
          type: "doc",
          id: "reference/openapi/get-web-authn-java-script",
          label: "Get WebAuthn JavaScript",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-flow-error",
          label: "Get User-Flow Errors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-fedcm-flow",
          label: "Get FedCM Parameters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-fedcm-flow",
          label: "Submit a FedCM token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/update-login-flow",
          label: "Submit a Login Flow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-native-login-flow",
          label: "Create Login Flow for Native Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-browser-login-flow",
          label: "Create Login Flow for Browsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-login-flow",
          label: "Get Login Flow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-test-login-flow",
          label: "Delete a test OIDC login flow",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/update-logout-flow",
          label: "Update Logout Flow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/perform-native-logout",
          label: "Perform Logout for Native Apps",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/create-browser-logout-flow",
          label: "Create a Logout URL for Browsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-recovery-flow",
          label: "Update Recovery Flow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-native-recovery-flow",
          label: "Create Recovery Flow for Native Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-browser-recovery-flow",
          label: "Create Recovery Flow for Browsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-recovery-flow",
          label: "Get Recovery Flow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-registration-flow",
          label: "Update Registration Flow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-native-registration-flow",
          label: "Create Registration Flow for Native Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-browser-registration-flow",
          label: "Create Registration Flow for Browsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-registration-flow",
          label: "Get Registration Flow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-settings-flow",
          label: "Complete Settings Flow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-native-settings-flow",
          label: "Create Settings Flow for Native Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-browser-settings-flow",
          label: "Create Settings Flow for Browsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-settings-flow",
          label: "Get Settings Flow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-verification-flow",
          label: "Complete Verification Flow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-native-verification-flow",
          label: "Create Verification Flow for Native Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-browser-verification-flow",
          label: "Create Verification Flow for Browser Clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-verification-flow",
          label: "Get Verification Flow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/disable-my-other-sessions",
          label: "Disable my other sessions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/list-my-sessions",
          label: "Get My Active Sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/exchange-session-token",
          label: "Exchange Session Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/to-session",
          label: "Check Who the Current HTTP Session Belongs To",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/disable-my-session",
          label: "Disable one of my sessions",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "courier",
      items: [
        {
          type: "doc",
          id: "reference/openapi/list-courier-messages",
          label: "List Messages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-courier-message",
          label: "Get a Message",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "metadata",
      items: [
        {
          type: "doc",
          id: "reference/openapi/get-version",
          label: "Return Running Software Version.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "wellknown",
      items: [
        {
          type: "doc",
          id: "reference/openapi/discover-json-web-keys",
          label: "Discover Well-Known JSON Web Keys",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "oidc",
      items: [
        {
          type: "doc",
          id: "reference/openapi/discover-oidc-configuration",
          label: "OpenID Connect Discovery",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-verifiable-credential",
          label: "Issues a Verifiable Credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/create-oidc-dynamic-client",
          label:
            "Register OAuth2 Client using OpenID Dynamic Client Registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-oidc-dynamic-client",
          label:
            "Delete OAuth 2.0 Client using the OpenID Dynamic Client Registration Management Protocol",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-oidc-dynamic-client",
          label: "Get OAuth2 Client using OpenID Dynamic Client Registration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/set-oidc-dynamic-client",
          label: "Set OAuth2 Client using OpenID Dynamic Client Registration",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/revoke-oidc-session",
          label: "OpenID Connect Front- and Back-channel Enabled Logout",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/get-oidc-user-info",
          label: "OpenID Connect Userinfo",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "oAuth2",
      items: [
        {
          type: "doc",
          id: "reference/openapi/list-o-auth-2-clients",
          label: "List OAuth 2.0 Clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-o-auth-2-client",
          label: "Create OAuth 2.0 Client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-o-auth-2-client",
          label: "Delete OAuth 2.0 Client",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-o-auth-2-client",
          label: "Get an OAuth 2.0 Client",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/patch-o-auth-2-client",
          label: "Patch OAuth 2.0 Client",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/set-o-auth-2-client",
          label: "Set OAuth 2.0 Client",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/set-o-auth-2-client-lifespans",
          label: "Set OAuth2 Client Token Lifespans",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/get-o-auth-2-consent-request",
          label: "Get OAuth 2.0 Consent Request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/accept-o-auth-2-consent-request",
          label: "Accept OAuth 2.0 Consent Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/reject-o-auth-2-consent-request",
          label: "Reject OAuth 2.0 Consent Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/accept-user-code-request",
          label: "Accepts a device grant user_code request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/get-o-auth-2-login-request",
          label: "Get OAuth 2.0 Login Request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/accept-o-auth-2-login-request",
          label: "Accept OAuth 2.0 Login Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/reject-o-auth-2-login-request",
          label: "Reject OAuth 2.0 Login Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/get-o-auth-2-logout-request",
          label: "Get OAuth 2.0 Session Logout Request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/accept-o-auth-2-logout-request",
          label: "Accept OAuth 2.0 Session Logout Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/reject-o-auth-2-logout-request",
          label: "Reject OAuth 2.0 Session Logout Request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/revoke-o-auth-2-consent-sessions",
          label: "Revoke OAuth 2.0 Consent Sessions of a Subject",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/list-o-auth-2-consent-sessions",
          label: "List OAuth 2.0 Consent Sessions of a Subject",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/revoke-o-auth-2-login-sessions",
          label:
            "Revokes OAuth 2.0 Login Sessions by either a Subject or a SessionID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/introspect-o-auth-2-token",
          label: "Introspect OAuth2 Access and Refresh Tokens",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-o-auth-2-token",
          label:
            "Delete OAuth 2.0 Access Tokens from specific OAuth 2.0 Client",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/list-trusted-o-auth-2-jwt-grant-issuers",
          label: "List Trusted OAuth2 JWT Bearer Grant Type Issuers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/trust-o-auth-2-jwt-grant-issuer",
          label: "Trust OAuth2 JWT Bearer Grant Type Issuer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-trusted-o-auth-2-jwt-grant-issuer",
          label: "Delete Trusted OAuth2 JWT Bearer Grant Type Issuer",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-trusted-o-auth-2-jwt-grant-issuer",
          label: "Get Trusted OAuth2 JWT Bearer Grant Type Issuer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/o-auth-2-authorize",
          label: "OAuth 2.0 Authorize Endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/o-auth-2-device-flow",
          label: "The OAuth 2.0 Device Authorize Endpoint",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/perform-o-auth-2-device-verification-flow",
          label: "OAuth 2.0 Device Verification Endpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/revoke-o-auth-2-token",
          label: "Revoke OAuth 2.0 Access or Refresh Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/oauth-2-token-exchange",
          label: "The OAuth 2.0 Token Endpoint",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "jwk",
      items: [
        {
          type: "doc",
          id: "reference/openapi/delete-json-web-key-set",
          label: "Delete JSON Web Key Set",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-json-web-key-set",
          label: "Retrieve a JSON Web Key Set",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-json-web-key-set",
          label: "Create JSON Web Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/set-json-web-key-set",
          label: "Update a JSON Web Key Set",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-json-web-key",
          label: "Delete JSON Web Key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-json-web-key",
          label: "Get JSON Web Key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/set-json-web-key",
          label: "Set JSON Web Key",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "relationship",
      items: [
        {
          type: "doc",
          id: "reference/openapi/delete-relationships",
          label: "Delete Relationships",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/patch-relationships",
          label: "Patch Multiple Relationships",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/create-relationship",
          label: "Create a Relationship",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/list-relationship-namespaces",
          label: "Query namespaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/check-opl-syntax",
          label: "Check the syntax of an OPL file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/get-relationships",
          label: "Query relationships",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "project",
      items: [
        {
          type: "doc",
          id: "reference/openapi/list-projects",
          label: "List All Projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-project",
          label: "Create a Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/purge-project",
          label: "Irrecoverably purge a project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-project",
          label: "Get a Project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/patch-project",
          label: "Patch an Ory Network Project Configuration",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/set-project",
          label: "Update an Ory Network Project Configuration",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/list-organizations",
          label: "List all Enterprise SSO organizations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-organization",
          label: "Create an Enterprise SSO Organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-organization",
          label: "Delete Enterprise SSO Organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/get-organization",
          label: "Get Enterprise SSO Organization by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-organization",
          label: "Update an Enterprise SSO Organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/get-organization-onboarding-portal-links",
          label: "Get the organization onboarding portal links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-organization-onboarding-portal-link",
          label: "Create organization onboarding portal link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-organization-onboarding-portal-link",
          label: "Delete an organization onboarding portal link",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/update-organization-onboarding-portal-link",
          label: "Update organization onboarding portal link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/patch-project-with-revision",
          label:
            "Patch an Ory Network Project Configuration based on a revision ID",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "reference/openapi/get-project-members",
          label: "Get all members associated with this project",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/remove-project-member",
          label: "Remove a member associated with this project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/list-project-api-keys",
          label: "List a project's API keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-project-api-key",
          label: "Create project API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-project-api-key",
          label: "Delete project API key",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "events",
      items: [
        {
          type: "doc",
          id: "reference/openapi/list-event-streams",
          label:
            "List all event streams for the project. This endpoint is not paginated.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-event-stream",
          label: "Create an event stream for your project.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-event-stream",
          label: "Remove an event stream from a project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "reference/openapi/set-event-stream",
          label: "Update an event stream for a project.",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "permission",
      items: [
        {
          type: "doc",
          id: "reference/openapi/batch-check-permission",
          label: "Batch check permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/check-permission-or-error",
          label: "Check a permission",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/post-check-permission-or-error",
          label: "Check a permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/check-permission",
          label: "Check a permission",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/post-check-permission",
          label: "Check a permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/expand-permissions",
          label: "Expand a Relationship into permissions.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "workspace",
      items: [
        {
          type: "doc",
          id: "reference/openapi/list-workspaces",
          label: "List workspaces the user is a member of",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-workspace",
          label: "Create a new workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/get-workspace",
          label: "Get a workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/update-workspace",
          label: "Update an workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reference/openapi/list-workspace-projects",
          label: "List all projects of a workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/list-workspace-api-keys",
          label: "List a workspace's API keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "reference/openapi/create-workspace-api-key",
          label: "Create workspace API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "reference/openapi/delete-workspace-api-key",
          label: "Delete workspace API key",
          className: "api-method delete",
        },
      ],
    },
  ],
}

export default sidebar.apisidebar
