// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// sidebars-oss.ts

import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

const ossSidebar = [
  {
    type: "category",
    label: "Ory Open Source",
    items: [
      "oss/getting-started/index",
      "ecosystem/projects",
      "open-source",
      "ecosystem/community",
      "ecosystem/contributing",
      "open-source/commitment",
      "ecosystem/software-architecture-philosophy",
      {
        type: "category",
        label: "Guidelines",
        items: [
          "open-source/guidelines/rest-api-guidelines",
          "kratos/guides/e2e-integration-tests",
        ],
      },
    ],
  },
  {
    type: "doc",
    label: "Ory Kratos",
    id: "kratos/quickstart",
  },
  {
    type: "doc",
    label: "Ory Hydra",
    id: "hydra/self-hosted/quickstart",
  },
  {
    type: "doc",
    label: "Ory Keto",
    id: "keto/quickstart",
  },
  {
    type: "doc",
    label: "Ory Polis",
    id: "polis/quickstart",
  },
  {
    type: "doc",
    label: "Ory Oathkeeper",
    id: "oathkeeper/index",
  },
  "self-hosted/deployment",
  "ecosystem/configuring",
  {
    type: "category",
    label: "Operations and SRE",
    items: [
      {
        type: "autogenerated",
        dirName: "self-hosted/operations",
      },
    ],
  },
  "ecosystem/upgrading",
  "ecosystem/sqa",
  "ecosystem/changelog",
]
export default ossSidebar
