// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// sidebars.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

import { SidebarItemConfig } from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

// sidebars.ts
//import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// adjust imports depending on how those files export
import networkSidebar from "./sidebars-network"
import oelSidebar from "./sidebars-oel"
import ossSidebar from "./sidebars-oss"
import agenticSidebar from "./sidebars-agentic"
import ciamSidebar from "./sidebars-ciam"
import b2bSidebar from "./sidebars-b2b"
import workforceSidebar from "./sidebars-workforce"
import quickstartsSidebar, {
  quickstartsNetworkSidebar,
  quickstartsOelSidebar,
  quickstartsOssSidebar,
} from "./sidebars-quickstarts"

const cli: SidebarItemsConfig = [
  {
    type: "category",
    label: "Ory CLI reference",
    collapsed: false,
    collapsible: false,
    link: {
      type: "generated-index",
      slug: "/category/ory-cli-reference",
    },
    items: [
      "guides/cli/installation",
      "guides/cli/cli-basics",
      "guides/cli/identity-cli",
      "guides/cli/oauth2-cli",
      "guides/cli/configure-permission-service",
      "guides/cli/proxy-and-tunnel",
      "guides/cli/config-with-cli",
      {
        type: "category",
        label: "CLI commands reference",
        link: {
          type: "generated-index",
        },
        items: [
          {
            type: "autogenerated",
            dirName: "cli",
          },
        ],
      },
    ],
  },
]

const api: SidebarItemsConfig = [
  "reference/api",
  //"ecosystem/api-design",
  {
    type: "category",
    label: "Operations",
    collapsed: false,
    collapsible: false,
    link: {
      type: "generated-index",
      slug: "/category/operations-reference",
    },
    items: [
      "concepts/personal-access-token",
      "guides/cors",
      "guides/api-rest-pagination",
      "guides/rate-limits",
      "guides/ip-allowlist",
      "api/eventual-consistency",
      "kratos/reference/jsonnet",
      "guides/user-impersonation",
    ],
  },
]

const sidebars: SidebarsConfig = {
  networkSidebar,
  oelSidebar,
  ossSidebar,
  agenticSidebar,
  ciamSidebar,
  b2bSidebar,
  quickstartsSidebar,
  quickstartsNetworkSidebar,
  quickstartsOelSidebar,
  quickstartsOssSidebar,
  api,
  cli,
}

export default sidebars
