// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// sidebars-oss.ts

import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

const ossSidebar = [
  {
    type: "category",
    label: "Open Source",
    link: {
      type: "generated-index",
      slug: "/category/open-source",
    },
    items: [
      "oss/getting-started/index",
      "oss/projects",
      "oss/open-source",
      "oss/community",
      "oss/contributing",
      "oss/commitment",
      "oss/software-architecture-philosophy",
      {
        type: "category",
        label: "Guidelines",
        items: [
          "oss/guidelines/rest-api-guidelines",
          "oss/guidelines/e2e-integration-tests",
        ],
      },
      {
        type: "category",
        label: "Ory Kratos",
        items: [
          "kratos/quickstart",
        ],
      },
      {
        type: "category",
        label: "Ory Hydra",
        items: [
          "hydra/self-hosted/quickstart",
        ],
      },
      {
        type: "category",
        label: "Ory Keto",
        items: [
          "keto/quickstart",
        ],
      },
      {
        type: "category",
        label: "Ory Polis",
        items: [
          "polis/quickstart",
        ],
      },
      {
        type: "category",
        label: "Ory Oathkeeper",
        items: [
          "oathkeeper/index",
        ],
      },
      "oss/deployment",
      "oss/configuring",
      {
        type: "category",
        label: "Operations and SRE",
        items: [
          {
            type: "autogenerated",
            dirName: "self-hosted/operations",
          },
        ],
      },
      "oss/upgrading",
      "oss/sqa",
      "oss/changelog",
    ],
  },
]

export default ossSidebar
