// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// sidebars.ts
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

import { SidebarItemConfig } from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

// sidebars.ts
//import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// adjust imports depending on how those files export
import oelSidebar from "./sidebars-oel"
import networkSidebar from "./sidebars-network"
import ossSidebar from "./sidebars-oss"
import agenticSidebar from "./sidebars-agentic"
import ciamSidebar from "./sidebars-ciam"
import b2bSidebar from "./sidebars-b2b"
import workforceSidebar from "./sidebars-workforce"
import quickstartsSidebar, {
  quickstartsNetworkSidebar,
  quickstartsNetworkOnlySidebar,
  quickstartsOelSidebar,
  quickstartsOssSidebar,
} from "./sidebars-quickstarts"

const cli: SidebarItemsConfig = [
  {
    type: "category",
    label: "Ory CLI reference",
    collapsed: false,
    collapsible: false,
    link: {
      type: "generated-index",
      slug: "/category/ory-cli-reference",
    },
    items: [
      "guides/cli/installation",
      "guides/cli/cli-basics",
      "guides/cli/identity-cli",
      "guides/cli/oauth2-cli",
      "guides/cli/configure-permission-service",
      "guides/cli/proxy-and-tunnel",
      "guides/cli/config-with-cli",
      {
        type: "category",
        label: "CLI commands reference",
        link: {
          type: "generated-index",
        },
        items: [
          {
            type: "autogenerated",
            dirName: "cli",
          },
        ],
      },
    ],
  },
]

const api: SidebarItemsConfig = [
  "reference/api",
  "ecosystem/api-design",
  {
    type: "category",
    label: "Operations",
    collapsed: false,
    collapsible: false,
    link: {
      type: "generated-index",
      slug: "/category/operations-reference",
    },
    items: [
      "concepts/personal-access-token",
      "guides/cors",
      "guides/api-rest-pagination",
      "guides/rate-limits",
      "guides/ip-allowlist",
      "api/eventual-consistency",
      "kratos/reference/jsonnet",
      "guides/user-impersonation",
    ],
  },
]

const troubleshooting: SidebarItemsConfig = [
  {
    type: "category",
    label: "Troubleshooting",
    collapsible: false,
    collapsed: false,
    link: {
      type: "generated-index",
      slug: "/category/troubleshooting-reference",
    },
    items: [
      {
        type: "autogenerated",
        dirName: "troubleshooting",
      },
      "oauth2-oidc/identity-provider-integration-settings",
      "guides/upgrade/sdk-v1",
      "hydra/debug",
      "hydra/debug/logout",
      "hydra/debug/token-endpoint-auth-method",
    ],
  },
]

const security: SidebarItemsConfig = [
  {
    type: "category",
    label: "Security and compliance",
    collapsible: false,
    collapsed: false,
    link: {
      type: "generated-index",
      slug: "/category/security-compliance",
    },
    items: [
      {
        type: "autogenerated",
        dirName: "security-compliance",
      },
      "kratos/concepts/security",
      "concepts/password-policy",
      "hydra/security-architecture",
    ],
  },
]


const sidebars: SidebarsConfig = {
  networkSidebar,
  oelSidebar,
  ossSidebar,
  agenticSidebar,
  ciamSidebar,
  b2bSidebar,
  workforceSidebar,
  quickstartsSidebar,
  quickstartsNetworkSidebar,
  quickstartsNetworkOnlySidebar,
  quickstartsOelSidebar,
  quickstartsOssSidebar,
  api,
  cli,
  troubleshooting,
  security,
}

export default sidebars
