import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"
import talosApiSidebar from "./docs/talos/reference/api/sidebar"
import talosCliReference from "./docs/talos/reference/cli/sidebar"

type SidebarItemsConfig = SidebarItemConfig[]

// The generated Talos API sidebar is [overview doc, { category "ApiKeys", items: [...methods] }].
// Lift the methods into a single "API reference" category linked to the overview page so the
// navigation reads cleanly instead of exposing the raw OpenAPI tag name.
const talosApiReference = {
  type: "category",
  label: "API reference",
  link: { type: "doc", id: "talos/reference/api/ory-talos-api" },
  items: talosApiSidebar.flatMap((item: any) =>
    typeof item === "object" && "items" in item && Array.isArray(item.items)
      ? item.items
      : [],
  ),
}

const oelSidebar = [
  {
    type: "category",
    label: "Ory Enterprise License",
    collapsed: false,
    collapsible: false,
    link: {
      type: "doc",
      id: "oel/getting-started/index",
    },
    items: [
      "oel/getting-started/index",
      {
        type: "category",
        label: "Getting started",
        collapsed: true,
        collapsible: true,
        items: [
          "self-hosted/oel/quickstart",
          "self-hosted/oel/monitoring/monitoring",
          "self-hosted/oel/high-performance-pooling",
        ],
      },
      {
        type: "category",
        label: "Ory Kratos",
        className: "sidebar-icon sidebar-icon-kratos",
        items: [
          "oel/kratos/intro",
          "oel/kratos/install",
          "self-hosted/oel/kratos/upgrade",
          "self-hosted/oel/kratos/changelog",
          "oel/kratos/quickstart",
          {
            type: "category",
            label: "Configuration",
            items: [
              "kratos/configuring",
              "self-hosted/oel/kratos/configuration",
              "kratos/guides/configuring-cookies",
              "kratos/guides/multi-domain-cookies",
              "self-hosted/kratos/configuration/password",
              "kratos/self-hosted/mfa",
              "kratos/guides/setting-up-cors",
              "self-hosted/kratos/configuration/oidc",
              "kratos/guides/setting-up-password-hashing-parameters",
              "kratos/guides/select-cipher-algorithm",
              "kratos/self-hosted/email-http",
              "kratos/reference/configuration-editor",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "kratos/guides/docker",
              "kratos/guides/deploy-kratos-example",
              "kratos/guides/upgrade",
              "kratos/guides/production",
              "kratos/guides/multi-tenancy-multitenant",
              "oel/kratos/scalability",
              "kratos/self-hosted/mail-courier-templates",
              "kratos/guides/tracing",
              "kratos/guides/zero-trust-iap-proxy-identity-access-proxy",
              "kratos/guides/https-tls",
              "kratos/guides/hosting-own-have-i-been-pwned-api",
              "kratos/guides/secret-key-rotation",
              "kratos/passwordless/deviceauthn",
              {
                type: "category",
                label: "Troubleshooting",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "kratos/debug",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "kratos/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "kratos/cli",
                  },
                ],
              },
              {
                SDK: ["kratos/sdk/overview", "kratos/self-hosted/go"],
              },
              "kratos/reference/configuration",
              "kratos/reference/json-schema-json-paths",
              "kratos/reference/html-forms",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Keto",
        className: "sidebar-icon sidebar-icon-keto",
        items: [
          "oel/keto/index",
          "oel/keto/install",
          "keto/guides/v0.7-migration",
          "keto/guides/migrating-legacy-policies",
          "keto/guides/upgrade",
          "oel/keto/quickstart",
          "self-hosted/oel/keto/changelog",
          {
            type: "category",
            label: "Configuration",
            items: [
              "self-hosted/oel/keto/configuration",
              "keto/reference/configuration-editor",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: ["keto/guides/production"],
          },
          {
            Reference: [
              "keto/reference/rest-api",
              "keto/reference/proto-api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "keto/cli",
                  },
                ],
              },
              {
                SDK: ["keto/sdk/overview", "keto/self-hosted/go"],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Hydra",
        className: "sidebar-icon sidebar-icon-hydra",
        items: [
          "oel/hydra/index",
          "hydra/self-hosted/install",
          "self-hosted/oel/oauth2/migrate",
          "self-hosted/oel/oauth2/revert-database-migrations",
          "self-hosted/oel/oauth2/upgrade",
          "hydra/self-hosted/upgrade",
          "self-hosted/oel/oauth2/changelog",
          "oel/hydra/quickstart",
          {
            type: "category",
            label: "Configuration",
            collapsed: true,
            collapsible: true,
            items: [
              "self-hosted/oel/oauth2/configuration",
              "hydra/reference/configuration-editor",
              "hydra/self-hosted/dependencies-environment",
              "self-hosted/oel/oauth2/token-prefix",
              "self-hosted/oel/oauth2/stateless-jwt",
              "self-hosted/oel/oauth2/migrate-postgresql-ttl",
              "hydra/self-hosted/hsm-support",
              "oel/hydra/tracing",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "hydra/self-hosted/configure-deploy",
              "hydra/self-hosted/gitlab",
              "hydra/self-hosted/merge-multiple-db-secrets",
              "hydra/self-hosted/secrets-key-rotation",
              "hydra/self-hosted/ssl-https-tls",
              "hydra/guides/cookies",
              "hydra/guides/cors",
              "self-hosted/hydra/debug/csrf",
              "hydra/self-hosted/production",
              "hydra/self-hosted/deploy-hydra-example",
              "hydra/self-hosted/kubernetes-helm-chart",
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "hydra/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "hydra/cli",
                  },
                ],
              },
              {
                SDK: [
                  "hydra/sdk/overview",
                  "hydra/self-hosted/go",
                  "hydra/self-hosted/js",
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Polis",
        className: "sidebar-icon sidebar-icon-polis",
        collapsed: true,
        collapsible: true,
        items: [
          "oel/polis/index",
          "polis/install",
          "self-hosted/oel/polis/changelog",
          "oel/polis/quickstart",
          {
            type: "category",
            label: "Enterprise SSO",
            collapsed: false,
            collapsible: false,
            link: {
              type: "doc",
              id: "polis/saml-federation/index",
            },
            items: [
              {
                type: "category",
                label: "Concepts",
                link: {
                  type: "doc",
                  id: "polis/sso-flow/index",
                },
                items: [
                  "polis/sso-flow/index",
                  "polis/sso-flow/example-flow",
                  "polis/security",
                ],
              },
              {
                type: "category",
                label: "Configuration",
                items: [
                  "polis/deploy/env-variables",
                  "polis/guides/configuring-saml-sso",
                  "polis/guides/login-with-saml-sso",
                  "polis/deploy/pre-loaded-connections",
                ],
              },
              {
                type: "category",
                label: "Guides",
                link: {
                  type: "doc",
                  id: "polis/guides/service",
                },
                items: [
                  "polis/guides/service",
                  "polis/guides/npm-library",
                  "polis/upgrade",
                  "polis/guides/examples",
                  "polis/sbom",
                  "polis/container-signing",
                  "polis/events",
                  "polis/observability",
                  {
                    type: "category",
                    label: "Frameworks",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "polis/guides/frameworks",
                      },
                    ],
                  },
                  {
                    type: "category",
                    label: "Deployment",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "polis/guides/deployment",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "SAML SSO Providers",
                link: {
                  type: "doc",
                  id: "polis/sso-providers/index",
                },
                items: [
                  {
                    type: "autogenerated",
                    dirName: "polis/sso-providers",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Directory Sync",
            collapsed: false,
            collapsible: false,
            link: {
              type: "doc",
              id: "polis/directory-sync/index",
            },
            items: [
              "polis/directory-sync/quickstart",
              "polis/directory-sync/api-reference",
              {
                type: "category",
                label: "Guides",
                collapsed: true,
                link: {
                  type: "generated-index",
                },
                items: [
                  "polis/directory-sync/webhooks",
                  "polis/directory-sync/events",
                  "polis/directory-sync/observability",
                  "polis/directory-sync/examples",
                  "polis/directory-sync/faq",
                  {
                    type: "category",
                    label: "Directory providers",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "polis/directory-sync/providers",
                      },
                    ],
                  },
                  {
                    type: "category",
                    label: "Frameworks",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "polis/directory-sync/guides",
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Admin Portal",
            collapsed: false,
            collapsible: false,
            link: {
              type: "doc",
              id: "polis/admin-portal/index",
            },
            items: [
              {
                type: "category",
                label: "Guides",
                collapsed: true,
                link: {
                  type: "generated-index",
                },
                items: [
                  "polis/admin-portal/enterprise-sso",
                  "polis/admin-portal/setup-links-enterprise-sso",
                  "polis/admin-portal/directory-sync",
                  "polis/admin-portal/setup-links-directory-sync",
                ],
              },
            ],
          },
          "polis/reference/api",
        ],
      },
      {
        type: "category",
        label: "Ory Oathkeeper",
        className: "sidebar-icon sidebar-icon-oathkeeper",
        collapsed: true,
        collapsible: true,
        items: [
          "oel/oathkeeper/index",
          "oathkeeper/install",
          "self-hosted/oel/oathkeeper/upgrade-oathkeeper",
          "self-hosted/oel/oathkeeper/changelog",
          {
            type: "category",
            label: "Configure",
            collapsed: false,
            collapsible: false,
            items: [
              "self-hosted/oel/oathkeeper/configuration",
              "oathkeeper/reference/configuration-editor",
            ],
          },
          {
            type: "category",
            label: "Guides",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/guides/proxy-websockets",
              "oathkeeper/guides/traefik-proxy-integration",
              "oathkeeper/api-access-rules",
              {
                type: "category",
                label: "Handlers",
                items: [
                  "oathkeeper/pipeline",
                  "oathkeeper/pipeline/authn",
                  "oathkeeper/pipeline/authz",
                  "oathkeeper/pipeline/mutator",
                  "oathkeeper/pipeline/error",
                ],
              },
              "oathkeeper/grpc-middleware",
              "oel/oathkeeper/configure-deploy",
            ],
          },
          {
            type: "category",
            label: "Reference",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "oathkeeper/cli",
                  },
                ],
              },
              "oathkeeper/sdk",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Talos",
        className: "sidebar-icon sidebar-icon-talos",
        collapsed: true,
        collapsible: true,
        items: [
          "talos/index",
          {
            type: "category",
            label: "Quickstart",
            items: [
              "talos/quickstart/open-source",
              "talos/quickstart/docker-commercial",
            ],
          },
          {
            type: "category",
            label: "Concepts",
            items: [
              "talos/concepts/index",
              "talos/concepts/architecture",
              "talos/concepts/credential-types",
              "talos/concepts/token-format",
              "talos/concepts/security-model",
              "talos/concepts/caching",
              "talos/concepts/rate-limiting",
              "talos/concepts/ip-restrictions",
            ],
          },
          {
            type: "category",
            label: "Integrate",
            items: [
              "talos/integrate/index",
              "talos/integrate/issue-and-verify",
              "talos/integrate/import-keys",
              "talos/integrate/derive-tokens",
              "talos/integrate/batch-operations",
              "talos/integrate/key-lifecycle",
              "talos/integrate/self-revocation",
              "talos/integrate/ip-restrictions",
              "talos/integrate/rate-limiting",
              "talos/integrate/error-handling",
              {
                type: "category",
                label: "SDKs",
                items: ["talos/integrate/sdk/go", "talos/integrate/sdk/curl"],
              },
            ],
          },
          {
            type: "category",
            label: "Operate",
            items: [
              "talos/operate/index",
              "talos/operate/install",
              "talos/operate/configure",
              "talos/operate/benchmarks",
              {
                type: "category",
                label: "Database",
                items: [
                  "talos/operate/database/index",
                  "talos/operate/database/sqlite",
                  "talos/operate/database/postgresql",
                  "talos/operate/database/mysql",
                  "talos/operate/database/cockroachdb",
                  "talos/operate/database/migrations",
                ],
              },
              {
                type: "category",
                label: "Deploy",
                items: [
                  "talos/operate/deploy/index",
                  "talos/operate/deploy/docker",
                  "talos/operate/deploy/deployment-modes",
                  "talos/operate/deploy/edge-proxy",
                ],
              },
              "talos/operate/secrets",
              "talos/operate/tls",
              {
                type: "category",
                label: "Monitoring",
                items: [
                  "talos/operate/monitoring/index",
                  "talos/operate/monitoring/metrics",
                  "talos/operate/monitoring/tracing",
                  "talos/operate/monitoring/health-checks",
                ],
              },
              {
                type: "category",
                label: "Cache",
                items: [
                  "talos/operate/cache/index",
                  "talos/operate/cache/memory",
                  "talos/operate/cache/redis",
                ],
              },
              "talos/operate/multi-tenancy",
              "talos/operate/troubleshooting",
              "talos/operate/security-hardening",
              "talos/operate/security/admin-protection",
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "talos/reference/index",
              talosApiReference,
              talosCliReference,
              "talos/reference/config",
              "talos/reference/token-format",
              "talos/reference/events",
              "talos/reference/error-codes",
            ],
          },
        ],
      },
    ],
  },
]

export default oelSidebar
