// sidebars-integrates.ts
import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

const integratesSidebar = [
  {
    type: "category",
    label: "Integrations overview",
    link: {
      type: "generated-index",
      slug: "/integrations",
    },
    items: [
      {
        type: "category",
        label: "Agent identity",
        link: { type: "generated-index" },
        items: [
          "integrates-with/agent-identity/skyfire",
          "integrates-with/agent-identity/tetrate",
        ],
      },
      {
        type: "category",
        label: "API gateways",
        link: { type: "generated-index" },
        items: [
          "integrates-with/api-gateways/apigee",
          "integrates-with/api-gateways/aws-api-gateway",
          "integrates-with/api-gateways/envoy",
          "integrates-with/api-gateways/kong",
          "integrates-with/api-gateways/traefik",
        ],
      },
      {
        type: "category",
        label: "CDP and analytics",
        link: { type: "generated-index" },
        items: [
          "integrates-with/cdp-analytics/amplitude",
          "integrates-with/cdp-analytics/mailchimp",
          "integrates-with/cdp-analytics/mixpanel",
          "integrates-with/cdp-analytics/mparticle",
          "integrates-with/cdp-analytics/segment",
        ],
      },
      {
        type: "category",
        label: "Cloud infrastructure",
        link: { type: "generated-index" },
        items: [
          "integrates-with/cloud-infrastructure/aws",
          "integrates-with/cloud-infrastructure/azure",
          "integrates-with/cloud-infrastructure/gcp",
        ],
      },
      {
        type: "category",
        label: "Compliance and audit",
        link: { type: "generated-index" },
        items: [
          "integrates-with/compliance-audit/drata",
          "integrates-with/compliance-audit/vanta",
        ],
      },
      {
        type: "category",
        label: "Consent and privacy",
        link: { type: "generated-index" },
        items: [
          "integrates-with/consent-privacy/didomi",
          "integrates-with/consent-privacy/onetrust",
          "integrates-with/consent-privacy/osano",
        ],
      },
      {
        type: "category",
        label: "Containerization",
        link: { type: "generated-index" },
        items: [
          "integrates-with/containerization/docker",
          "integrates-with/containerization/kubernetes",
        ],
      },
      {
        type: "category",
        label: "CRM",
        link: { type: "generated-index" },
        items: [
          "integrates-with/crm/hubspot",
          "integrates-with/crm/microsoft-dynamics-365",
          "integrates-with/crm/pipedrive",
          "integrates-with/crm/salesforce",
          "integrates-with/crm/zoho-crm",
        ],
      },
      {
        type: "category",
        label: "Data persistence",
        items: ["integrates-with/data-persistence/cockroachdb"],
      },
      {
        type: "category",
        label: "Directory sync",
        link: { type: "generated-index" },
        items: [
          "integrates-with/directory-sync/bamboohr",
          "integrates-with/directory-sync/google-workspace-scim",
          "integrates-with/directory-sync/jumpcloud-scim",
          "integrates-with/directory-sync/microsoft-scim",
          "integrates-with/directory-sync/okta-scim",
          "integrates-with/directory-sync/onelogin-scim",
          "integrates-with/directory-sync/workday-scim",
        ],
      },
      {
        type: "category",
        label: "Edge token validation",
        link: { type: "generated-index" },
        items: [
          "integrates-with/edge-token-validation/akamai-edgeworkers",
          "integrates-with/edge-token-validation/cloudflare-workers",
          "integrates-with/edge-token-validation/fastly-compute",
        ],
      },
      {
        type: "category",
        label: "Email providers",
        link: { type: "generated-index" },
        items: [
          "integrates-with/email-providers/aws-ses",
          "integrates-with/email-providers/brevo",
          "integrates-with/email-providers/mailchimp-transactional",
          "integrates-with/email-providers/mailgun",
          "integrates-with/email-providers/postmark",
          "integrates-with/email-providers/sendgrid",
          "integrates-with/email-providers/sparkpost",
        ],
      },
      {
        type: "category",
        label: "Enterprise SSO",
        link: { type: "generated-index" },
        items: [
          "integrates-with/enterprise-sso/auth0-saml",
          "integrates-with/enterprise-sso/cyberark-identity",
          "integrates-with/enterprise-sso/forgerock-am",
          "integrates-with/enterprise-sso/generic-oidc",
          "integrates-with/enterprise-sso/generic-saml",
          "integrates-with/enterprise-sso/google-workspace",
          "integrates-with/enterprise-sso/hid-global",
          "integrates-with/enterprise-sso/ibm-security-verify",
          "integrates-with/enterprise-sso/jumpcloud",
          "integrates-with/enterprise-sso/keycloak",
          "integrates-with/enterprise-sso/microsoft-adfs",
          "integrates-with/enterprise-sso/microsoft-entra-id",
          "integrates-with/enterprise-sso/okta",
          "integrates-with/enterprise-sso/onelogin",
          "integrates-with/enterprise-sso/pingone",
          "integrates-with/enterprise-sso/rippling",
        ],
      },
      {
        type: "category",
        label: "Feature flags",
        link: { type: "generated-index" },
        items: [
          "integrates-with/feature-flags/launchdarkly",
          "integrates-with/feature-flags/split-io",
        ],
      },
      {
        type: "category",
        label: "Fraud and bot protection",
        link: { type: "generated-index" },
        items: [
          "integrates-with/fraud-bot-protection/arkose-labs",
          "integrates-with/fraud-bot-protection/castle",
          "integrates-with/fraud-bot-protection/cloudflare-turnstile",
          "integrates-with/fraud-bot-protection/hcaptcha",
          "integrates-with/fraud-bot-protection/recaptcha",
          "integrates-with/fraud-bot-protection/sift",
        ],
      },
      {
        type: "category",
        label: "Government identity",
        link: { type: "generated-index" },
        items: [
          "integrates-with/government-identity/aadhaar",
          "integrates-with/government-identity/bankid",
          "integrates-with/government-identity/eidas",
          "integrates-with/government-identity/idin",
        ],
      },
      {
        type: "category",
        label: "IaC and DevOps",
        items: [
          "integrates-with/iac-devops/helm",
          "integrates-with/iac-devops/pulumi",
          "integrates-with/iac-devops/terraform",
        ],
      },
      {
        type: "category",
        label: "Identity verification",
        link: { type: "generated-index" },
        items: [
          "integrates-with/identity-verification/equifax",
          "integrates-with/identity-verification/gbg-acuant",
          "integrates-with/identity-verification/id-me",
          "integrates-with/identity-verification/jumio",
          "integrates-with/identity-verification/lexisnexis",
          "integrates-with/identity-verification/onfido",
          "integrates-with/identity-verification/persona",
          "integrates-with/identity-verification/prove",
          "integrates-with/identity-verification/socure",
        ],
      },
      {
        type: "category",
        label: "MFA",
        link: { type: "generated-index" },
        items: [
          "integrates-with/mfa/duo-security",
          "integrates-with/mfa/okta-verify",
          "integrates-with/mfa/yubikey",
        ],
      },
      {
        type: "category",
        label: "Monitoring and observability",
        link: { type: "generated-index" },
        items: [
          "integrates-with/monitoring-observability/datadog",
          "integrates-with/monitoring-observability/new-relic",
          "integrates-with/monitoring-observability/opentelemetry",
          "integrates-with/monitoring-observability/prometheus-grafana",
        ],
      },
      {
        type: "category",
        label: "Payment and billing",
        link: { type: "generated-index" },
        items: [
          "integrates-with/payment-billing/recurly",
          "integrates-with/payment-billing/stripe",
        ],
      },
      {
        type: "category",
        label: "SIEM and security analytics",
        link: { type: "generated-index" },
        items: [
          "integrates-with/siem-security-analytics/elastic-siem",
          "integrates-with/siem-security-analytics/microsoft-sentinel",
          "integrates-with/siem-security-analytics/splunk",
          "integrates-with/siem-security-analytics/sumo-logic",
        ],
      },
      {
        type: "category",
        label: "SMS providers",
        link: { type: "generated-index" },
        items: [
          "integrates-with/sms-providers/messagebird",
          "integrates-with/sms-providers/plivo",
          "integrates-with/sms-providers/sinch",
          "integrates-with/sms-providers/twilio",
          "integrates-with/sms-providers/vonage",
          "integrates-with/sms-providers/whatsapp",
        ],
      },
      {
        type: "category",
        label: "Social sign-in",
        link: { type: "generated-index" },
        items: [
          "integrates-with/social-sign-in/amazon-lwa",
          "integrates-with/social-sign-in/apple",
          "integrates-with/social-sign-in/auth0",
          "integrates-with/social-sign-in/battle-net",
          "integrates-with/social-sign-in/dingtalk",
          "integrates-with/social-sign-in/discord",
          "integrates-with/social-sign-in/epic-games",
          "integrates-with/social-sign-in/facebook",
          "integrates-with/social-sign-in/github",
          "integrates-with/social-sign-in/github-app",
          "integrates-with/social-sign-in/gitlab",
          "integrates-with/social-sign-in/google",
          "integrates-with/social-sign-in/kakao",
          "integrates-with/social-sign-in/lark",
          "integrates-with/social-sign-in/line",
          "integrates-with/social-sign-in/linkedin",
          "integrates-with/social-sign-in/microsoft",
          "integrates-with/social-sign-in/naver",
          "integrates-with/social-sign-in/netid",
          "integrates-with/social-sign-in/patreon",
          "integrates-with/social-sign-in/salesforce",
          "integrates-with/social-sign-in/slack",
          "integrates-with/social-sign-in/spotify",
          "integrates-with/social-sign-in/steam",
          "integrates-with/social-sign-in/telegram",
          "integrates-with/social-sign-in/tiktok",
          "integrates-with/social-sign-in/twitch",
          "integrates-with/social-sign-in/uaepass",
          "integrates-with/social-sign-in/vk",
          "integrates-with/social-sign-in/wechat",
          "integrates-with/social-sign-in/x-twitter",
          "integrates-with/social-sign-in/yandex",
        ],
      },
      {
        type: "category",
        label: "Support and helpdesk",
        link: { type: "generated-index" },
        items: [
          "integrates-with/support-helpdesk/freshdesk",
          "integrates-with/support-helpdesk/intercom",
          "integrates-with/support-helpdesk/zendesk",
        ],
      },
      {
        type: "category",
        label: "User enrichment",
        link: { type: "generated-index" },
        items: [
          "integrates-with/user-enrichment/clearbit",
          "integrates-with/user-enrichment/fullcontact",
          "integrates-with/user-enrichment/zoominfo",
        ],
      },
      {
        type: "category",
        label: "Webhook infrastructure",
        link: { type: "generated-index" },
        items: [
          "integrates-with/webhook-infrastructure/hookdeck",
          "integrates-with/webhook-infrastructure/svix",
        ],
      },
      {
        type: "category",
        label: "Generic protocols",
        link: { type: "generated-index" },
        items: [
          "integrates-with/generic-protocols/generic-oidc",
          "integrates-with/generic-protocols/generic-saml",
        ],
      },
    ],
  },
]

export default integratesSidebar
