// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// sidebars-oel.ts

import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

const oelSidebar = [
  {
    type: "category",
    label: "Ory Enterprise License",
    collapsed: false,
    collapsible: false,
    link: {
      type: "doc",
      id: "oel/getting-started/index",
    },
    items: [
      "oel/getting-started/index",
      {
        type: "category",
        label: "Getting started",
        collapsed: true,
        collapsible: true,
        items: [
          "self-hosted/oel/quickstart",
          "self-hosted/oel/monitoring/monitoring",
          "self-hosted/oel/high-performance-pooling",
        ],
      },
      {
        type: "category",
        label: "Ory Kratos",
        items: [
          "self-hosted/oel/kratos/upgrade",
          "self-hosted/oel/kratos/changelog",
          "self-hosted/oel/kratos/configuration",
          "kratos/install",
          "kratos/quickstart",
          {
            type: "category",
            label: "Configuration",
            items: [
              "kratos/configuring",
              "kratos/guides/configuring-cookies",
              "kratos/guides/multi-domain-cookies",
              "self-hosted/kratos/configuration/password",
              "kratos/self-hosted/mfa",
              "kratos/guides/setting-up-cors",
              "self-hosted/kratos/configuration/oidc",
              "kratos/guides/setting-up-password-hashing-parameters",
              "kratos/guides/select-cipher-algorithm",
              "kratos/self-hosted/email-http",
              "kratos/reference/configuration-editor",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "kratos/guides/docker",
              "kratos/guides/deploy-kratos-example",
              "kratos/guides/upgrade",
              "kratos/guides/production",
              "kratos/guides/multi-tenancy-multitenant",
              "self-hosted/operations/scalability",
              "kratos/self-hosted/mail-courier-templates",
              "kratos/guides/tracing",
              "kratos/guides/zero-trust-iap-proxy-identity-access-proxy",
              "kratos/guides/https-tls",
              "kratos/guides/hosting-own-have-i-been-pwned-api",
              "kratos/guides/secret-key-rotation",
              {
                type: "category",
                label: "Troubleshooting",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "kratos/debug",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "kratos/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "kratos/cli",
                  },
                ],
              },
              {
                SDK: ["kratos/sdk/overview", "kratos/self-hosted/go"],
              },
              "kratos/reference/configuration",
              "kratos/reference/json-schema-json-paths",
              "kratos/reference/html-forms",
            ],
          },
          {
            type: "category",
            label: "Self-Hosted",
            collapsed: false,
            collapsible: false,
            link: {
              type: "doc",
              id: "kratos/quickstart",
            },
            items: [
              "kratos/install",
              "kratos/quickstart",
              {
                type: "category",
                label: "Configuration",
                items: [
                  "kratos/configuring",
                  "kratos/guides/configuring-cookies",
                  "kratos/guides/multi-domain-cookies",
                  "self-hosted/kratos/configuration/password",
                  "kratos/self-hosted/mfa",
                  "kratos/guides/setting-up-cors",
                  "self-hosted/kratos/configuration/oidc",
                  "kratos/guides/setting-up-password-hashing-parameters",
                  "kratos/guides/select-cipher-algorithm",
                  "kratos/self-hosted/email-http",
                  "kratos/reference/configuration-editor",
                ],
              },
              {
                type: "category",
                label: "Guides",
                items: [
                  "kratos/guides/docker",
                  "kratos/guides/deploy-kratos-example",
                  "kratos/guides/upgrade",
                  "kratos/guides/production",
                  "kratos/guides/multi-tenancy-multitenant",
                  "self-hosted/operations/scalability",
                  "kratos/self-hosted/mail-courier-templates",
                  "kratos/guides/tracing",
                  "kratos/guides/zero-trust-iap-proxy-identity-access-proxy",
                  "kratos/guides/https-tls",
                  "kratos/guides/hosting-own-have-i-been-pwned-api",
                  "kratos/guides/secret-key-rotation",
                  {
                    type: "category",
                    label: "Troubleshooting",
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "kratos/debug",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Reference",
                items: [
                  "kratos/reference/api",
                  {
                    "Command Line Interface (CLI)": [
                      {
                        type: "autogenerated",
                        dirName: "kratos/cli",
                      },
                    ],
                  },
                  {
                    SDK: ["kratos/sdk/overview", "kratos/self-hosted/go"],
                  },
                  "kratos/reference/configuration",
                  "kratos/reference/json-schema-json-paths",
                  "kratos/reference/html-forms",
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Hydra",
        items: [
          "self-hosted/oel/oauth2/migrate",
          "self-hosted/oel/oauth2/upgrade",
          "self-hosted/oel/oauth2/changelog",
          "self-hosted/oel/oauth2/token-prefix",
          "self-hosted/oel/oauth2/stateless-jwt",
          "self-hosted/oel/oauth2/migrate-postgresql-ttl",
          "self-hosted/oel/oauth2/revert-database-migrations",
          "self-hosted/oel/oauth2/configuration",
          {
            type: "category",
            label: "Self-Hosted",
            collapsed: false,
            collapsible: false,
            items: [
              "hydra/self-hosted/install",
              "hydra/self-hosted/quickstart",
            ],
          },
          {
            type: "category",
            label: "Configuration",
            collapsed: false,
            collapsible: false,
            items: [
              "hydra/reference/configuration",
              "hydra/reference/configuration-editor",
              "hydra/self-hosted/configure-deploy",
              "hydra/self-hosted/dependencies-environment",
              "hydra/self-hosted/production",
              "hydra/self-hosted/hsm-support",
              "self-hosted/operations/scalability",
              "hydra/self-hosted/merge-multiple-db-secrets",
              "hydra/self-hosted/gitlab",
              "hydra/self-hosted/secrets-key-rotation",
              "hydra/self-hosted/kubernetes-helm-chart",
              "hydra/self-hosted/ssl-https-tls",
              "self-hosted/operations/tracing",
              "hydra/guides/cookies",
              "hydra/guides/cors",
              "self-hosted/hydra/debug/csrf",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "hydra/self-hosted/deploy-hydra-example",
              "hydra/self-hosted/upgrade",
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "hydra/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "hydra/cli",
                  },
                ],
              },
              {
                SDK: [
                  "hydra/sdk/overview",
                  "hydra/self-hosted/go",
                  "hydra/self-hosted/js",
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Keto",
        items: [
          "self-hosted/oel/keto/changelog",
          "self-hosted/oel/keto/configuration",
          {
            type: "category",
            label: "Self-Hosted",
            collapsed: false,
            collapsible: false,
            items: [
              "keto/install",
              "keto/quickstart",
              {
                type: "category",
                label: "Configuration",
                items: [
                  "keto/reference/configuration",
                  "keto/reference/configuration-editor",
                ],
              },
              {
                type: "category",
                label: "Guides",
                items: [
                  "keto/guides/production",
                  "keto/guides/v0.7-migration",
                  "keto/guides/migrating-legacy-policies",
                  "keto/guides/upgrade",
                ],
              },
              {
                Reference: [
                  "keto/reference/rest-api",
                  "keto/reference/proto-api",
                  {
                    "Command Line Interface (CLI)": [
                      {
                        type: "autogenerated",
                        dirName: "keto/cli",
                      },
                    ],
                  },
                  {
                    SDK: ["keto/sdk/overview", "keto/self-hosted/go"],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Polis",
        items: [
          "self-hosted/oel/polis/changelog",
          {
            type: "category",
            label: "Ory Polis",
            collapsed: true,
            collapsible: true,
            items: [
              "polis/index",
              "polis/install",
              "polis/quickstart",
              "polis/reference/api",
              {
                type: "category",
                label: "Enterprise SSO",
                collapsed: false,
                collapsible: false,
                link: {
                  type: "doc",
                  id: "polis/saml-federation/index",
                },
                items: [
                  {
                    type: "category",
                    label: "Concepts",
                    link: {
                      type: "doc",
                      id: "polis/sso-flow/index",
                    },
                    items: [
                      "polis/sso-flow/index",
                      "polis/sso-flow/example-flow",
                      "polis/security",
                    ],
                  },
                  {
                    type: "category",
                    label: "Configuration",
                    items: [
                      "polis/deploy/env-variables",
                      "polis/guides/configuring-saml-sso",
                      "polis/guides/login-with-saml-sso",
                      "polis/deploy/pre-loaded-connections",
                    ],
                  },
                  {
                    type: "category",
                    label: "Guides",
                    link: {
                      type: "doc",
                      id: "polis/guides/service",
                    },
                    items: [
                      "polis/guides/service",
                      "polis/guides/npm-library",
                      "polis/upgrade",
                      "polis/guides/examples",
                      "polis/sbom",
                      "polis/container-signing",
                      "polis/events",
                      "polis/observability",
                      {
                        type: "category",
                        label: "Frameworks",
                        items: [
                          {
                            type: "autogenerated",
                            dirName: "polis/guides/frameworks",
                          },
                        ],
                      },
                      {
                        type: "category",
                        label: "Deployment",
                        items: [
                          {
                            type: "autogenerated",
                            dirName: "polis/guides/deployment",
                          },
                        ],
                      },
                    ],
                  },
                  {
                    type: "category",
                    label: "SAML SSO Providers",
                    link: {
                      type: "doc",
                      id: "polis/sso-providers/index",
                    },
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "polis/sso-providers",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Directory Sync",
                collapsed: false,
                collapsible: false,
                link: {
                  type: "doc",
                  id: "polis/directory-sync/index",
                },
                items: [
                  "polis/directory-sync/quickstart",
                  "polis/directory-sync/api-reference",
                  {
                    type: "category",
                    label: "Guides",
                    collapsed: true,
                    link: {
                      type: "generated-index",
                      // slug: "polis/directory-sync/guides",
                    },
                    items: [
                      "polis/directory-sync/webhooks",
                      "polis/directory-sync/events",
                      "polis/directory-sync/observability",
                      "polis/directory-sync/examples",
                      "polis/directory-sync/faq",
                      // {
                      //   type: "category",
                      //   label: "Directory providers",
                      //   link: {
                      //     type: "generated-index",
                      //     slug: "polis/directory-sync/providers",
                      //   },
                      // items: [
                      //   {
                      //     type: "autogenerated",
                      //     dirName: "polis/directory-sync/providers",
                      //  },
                      //],
                      // },
                      // {
                      //   type: "category",
                      //   label: "Frameworks",
                      // items: [
                      //   {
                      //     type: "autogenerated",
                      //     dirName: "polis/directory-sync/guides",
                      //   },
                      //],
                      // },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Admin Portal",
                collapsed: false,
                collapsible: false,
                link: {
                  type: "doc",
                  id: "polis/admin-portal/index",
                },
                items: [
                  {
                    type: "category",
                    label: "Guides",
                    collapsed: true,
                    link: {
                      type: "generated-index",
                      //slug: "polis/admin-portal/guides",
                    },
                    items: [
                      "polis/admin-portal/enterprise-sso",
                      "polis/admin-portal/setup-links-enterprise-sso",
                      "polis/admin-portal/directory-sync",
                      "polis/admin-portal/setup-links-directory-sync",
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Oathkeeper",
        collapsed: true,
        collapsible: true,
        items: [
          "self-hosted/oel/oathkeeper/upgrade-oathkeeper",
          "self-hosted/oel/oathkeeper/changelog",
          "self-hosted/oel/oathkeeper/configuration",
          "oathkeeper/index",
          "oathkeeper/install",
          "oathkeeper/reference/api",
          {
            type: "category",
            label: "Concepts",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/api-access-rules",
              {
                type: "category",
                label: "Handlers",
                items: [
                  "oathkeeper/pipeline",
                  "oathkeeper/pipeline/authn",
                  "oathkeeper/pipeline/authz",
                  "oathkeeper/pipeline/mutator",
                  "oathkeeper/pipeline/error",
                ],
              },
              "oathkeeper/grpc-middleware",
            ],
          },
          {
            type: "category",
            label: "Guides",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/configure-deploy",
              "oathkeeper/guides/proxy-websockets",
              "oathkeeper/guides/traefik-proxy-integration",
              "oathkeeper/guides/upgrade",
            ],
          },
          {
            type: "category",
            label: "Reference",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/reference/configuration",
              "oathkeeper/reference/configuration-editor",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "oathkeeper/cli",
                  },
                ],
              },
              "oathkeeper/sdk",
            ],
          },
        ],
      },
    ],
  },
]

export default oelSidebar
