import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

const oelSidebar = [
  {
    type: "category",
    label: "Ory Enterprise License",
    collapsed: false,
    collapsible: false,
    link: {
      type: "doc",
      id: "oel/getting-started/index",
    },
    items: [
      "oel/getting-started/index",
      {
        type: "category",
        label: "Getting started",
        collapsed: true,
        collapsible: true,
        items: [
          "self-hosted/oel/quickstart",
          "self-hosted/oel/monitoring/monitoring",
          "self-hosted/oel/high-performance-pooling",
        ],
      },
      {
        type: "category",
        label: "Ory Kratos",
        className: "sidebar-icon sidebar-icon-kratos",
        items: [
          "oel/kratos/intro",
          "kratos/install",
          "self-hosted/oel/kratos/upgrade",
          "self-hosted/oel/kratos/changelog",
          "oel/kratos/quickstart",
          {
            type: "category",
            label: "Configuration",
            items: [
              "kratos/configuring",
              "self-hosted/oel/kratos/configuration",
              "kratos/guides/configuring-cookies",
              "kratos/guides/multi-domain-cookies",
              "self-hosted/kratos/configuration/password",
              "kratos/self-hosted/mfa",
              "kratos/guides/setting-up-cors",
              "self-hosted/kratos/configuration/oidc",
              "kratos/guides/setting-up-password-hashing-parameters",
              "kratos/guides/select-cipher-algorithm",
              "kratos/self-hosted/email-http",
              "kratos/reference/configuration-editor",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "kratos/guides/docker",
              "kratos/guides/deploy-kratos-example",
              "kratos/guides/upgrade",
              "kratos/guides/production",
              "kratos/guides/multi-tenancy-multitenant",
              "oel/kratos/scalability",
              "kratos/self-hosted/mail-courier-templates",
              "kratos/guides/tracing",
              "kratos/guides/zero-trust-iap-proxy-identity-access-proxy",
              "kratos/guides/https-tls",
              "kratos/guides/hosting-own-have-i-been-pwned-api",
              "kratos/guides/secret-key-rotation",
              {
                type: "category",
                label: "Troubleshooting",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "kratos/debug",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "kratos/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "kratos/cli",
                  },
                ],
              },
              {
                SDK: ["kratos/sdk/overview", "kratos/self-hosted/go"],
              },
              "kratos/reference/configuration",
              "kratos/reference/json-schema-json-paths",
              "kratos/reference/html-forms",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Hydra",
        className: "sidebar-icon sidebar-icon-hydra",
        items: [
          "oel/hydra/index",
          "hydra/self-hosted/install",
          "self-hosted/oel/oauth2/migrate",
          "self-hosted/oel/oauth2/revert-database-migrations",
          "self-hosted/oel/oauth2/upgrade",
          "hydra/self-hosted/upgrade",
          "self-hosted/oel/oauth2/changelog",
          "oel/hydra/quickstart",
          {
            type: "category",
            label: "Configuration",
            collapsed: true,
            collapsible: true,
            items: [
              "self-hosted/oel/oauth2/configuration",
              "hydra/reference/configuration-editor",
              "hydra/self-hosted/dependencies-environment",
              "self-hosted/oel/oauth2/token-prefix",
              "self-hosted/oel/oauth2/stateless-jwt",
              "self-hosted/oel/oauth2/migrate-postgresql-ttl",
              "hydra/self-hosted/hsm-support",
              "oel/hydra/tracing",
            ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "hydra/self-hosted/configure-deploy",
              "hydra/self-hosted/gitlab",
              "hydra/self-hosted/merge-multiple-db-secrets",
              "hydra/self-hosted/secrets-key-rotation",
              "hydra/self-hosted/ssl-https-tls",
              "hydra/guides/cookies",
              "hydra/guides/cors",
              "self-hosted/hydra/debug/csrf",
              "oel/hydra/scalability",
              "hydra/self-hosted/production",
              "hydra/self-hosted/deploy-hydra-example",
              "hydra/self-hosted/kubernetes-helm-chart",
            ],
          },
          {
            type: "category",
            label: "Reference",
            items: [
              "hydra/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "hydra/cli",
                  },
                ],
              },
              {
                SDK: [
                  "hydra/sdk/overview",
                  "hydra/self-hosted/go",
                  "hydra/self-hosted/js",
                ],
              },
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Ory Keto",
        className: "sidebar-icon sidebar-icon-keto",
        items: [
          "oel/keto/index",
          "keto/install",
          "keto/guides/v0.7-migration",
          "keto/guides/migrating-legacy-policies",
          "keto/guides/upgrade",
          "oel/keto/quickstart",
          "self-hosted/oel/keto/changelog",
          {
            type: "category",
            label: "Configuration",
            items: [
              "self-hosted/oel/keto/configuration",
              "keto/reference/configuration-editor",
              ],
          },
          {
            type: "category",
            label: "Guides",
            items: [
              "keto/guides/production",
              ],
          },
          {
            Reference: [
              "keto/reference/rest-api",
              "keto/reference/proto-api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "keto/cli",
                  },
                ],
              },
              {
                SDK: ["keto/sdk/overview", "keto/self-hosted/go"],
              },
              ],
          },
        ],
      },
          {
            type: "category",
            label: "Ory Polis",
            className: "sidebar-icon sidebar-icon-polis",
            collapsed: true,
            collapsible: true,
            items: [
              "oel/polis/index",
              "polis/install",
              "self-hosted/oel/polis/changelog",
              "oel/polis/quickstart",
              {
                type: "category",
                label: "Enterprise SSO",
                collapsed: false,
                collapsible: false,
                link: {
                  type: "doc",
                  id: "polis/saml-federation/index",
                },
                items: [
                  {
                    type: "category",
                    label: "Concepts",
                    link: {
                      type: "doc",
                      id: "polis/sso-flow/index",
                    },
                    items: [
                      "polis/sso-flow/index",
                      "polis/sso-flow/example-flow",
                      "polis/security",
                    ],
                  },
                  {
                    type: "category",
                    label: "Configuration",
                    items: [
                      "polis/deploy/env-variables",
                      "polis/guides/configuring-saml-sso",
                      "polis/guides/login-with-saml-sso",
                      "polis/deploy/pre-loaded-connections",
                    ],
                  },
                  {
                    type: "category",
                    label: "Guides",
                    link: {
                      type: "doc",
                      id: "polis/guides/service",
                    },
                    items: [
                      "polis/guides/service",
                      "polis/guides/npm-library",
                      "polis/upgrade",
                      "polis/guides/examples",
                      "polis/sbom",
                      "polis/container-signing",
                      "polis/events",
                      "polis/observability",
                      {
                        type: "category",
                        label: "Frameworks",
                        items: [
                          {
                            type: "autogenerated",
                            dirName: "polis/guides/frameworks",
                          },
                        ],
                      },
                      {
                        type: "category",
                        label: "Deployment",
                        items: [
                          {
                            type: "autogenerated",
                            dirName: "polis/guides/deployment",
                          },
                        ],
                      },
                    ],
                  },
                  {
                    type: "category",
                    label: "SAML SSO Providers",
                    link: {
                      type: "doc",
                      id: "polis/sso-providers/index",
                    },
                    items: [
                      {
                        type: "autogenerated",
                        dirName: "polis/sso-providers",
                      },
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Directory Sync",
                collapsed: false,
                collapsible: false,
                link: {
                  type: "doc",
                  id: "polis/directory-sync/index",
                },
                items: [
                  "polis/directory-sync/quickstart",
                  "polis/directory-sync/api-reference",
                  {
                    type: "category",
                    label: "Guides",
                    collapsed: true,
                    link: {
                      type: "generated-index",
                    },
                    items: [
                      "polis/directory-sync/webhooks",
                      "polis/directory-sync/events",
                      "polis/directory-sync/observability",
                      "polis/directory-sync/examples",
                      "polis/directory-sync/faq",
                    ],
                  },
                ],
              },
              {
                type: "category",
                label: "Admin Portal",
                collapsed: false,
                collapsible: false,
                link: {
                  type: "doc",
                  id: "polis/admin-portal/index",
                },
                items: [
                  {
                    type: "category",
                    label: "Guides",
                    collapsed: true,
                    link: {
                      type: "generated-index",
                    },
                    items: [
                      "polis/admin-portal/enterprise-sso",
                      "polis/admin-portal/setup-links-enterprise-sso",
                      "polis/admin-portal/directory-sync",
                      "polis/admin-portal/setup-links-directory-sync",
                    ],
                  },
                ],
              },
              "polis/reference/api",
            ],
          },
      {
        type: "category",
        label: "Ory Oathkeeper",
        className: "sidebar-icon sidebar-icon-oathkeeper",
        collapsed: true,
        collapsible: true,
        items: [
          "oel/oathkeeper/index",
          "oathkeeper/install",
          "self-hosted/oel/oathkeeper/upgrade-oathkeeper",
          "self-hosted/oel/oathkeeper/changelog",
          {
            type: "category",
            label: "Configure",
            collapsed: false,
            collapsible: false,
            items: [
              "self-hosted/oel/oathkeeper/configuration",
              "oathkeeper/reference/configuration-editor",
            ],
          },
          {
            type: "category",
            label: "Guides",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/guides/proxy-websockets",
              "oathkeeper/guides/traefik-proxy-integration",
              "oathkeeper/api-access-rules",
              {
                type: "category",
                label: "Handlers",
                items: [
                  "oathkeeper/pipeline",
                  "oathkeeper/pipeline/authn",
                  "oathkeeper/pipeline/authz",
                  "oathkeeper/pipeline/mutator",
                  "oathkeeper/pipeline/error",
                ],
              },
              "oathkeeper/grpc-middleware",
              "oel/oathkeeper/configure-deploy",
            ],
          },
          {
            type: "category",
            label: "Reference",
            collapsed: false,
            collapsible: false,
            items: [
              "oathkeeper/reference/api",
              {
                "Command Line Interface (CLI)": [
                  {
                    type: "autogenerated",
                    dirName: "oathkeeper/cli",
                  },
                ],
              },
              "oathkeeper/sdk",
            ],
          },
        ],
      },
    ],
  },
]

export default oelSidebar