// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// sidebars-oss.ts

import {
  SidebarItem,
  SidebarItemConfig,
} from "@docusaurus/plugin-content-docs/src/sidebars/types"

type SidebarItemsConfig = SidebarItemConfig[]

const ossSidebar = [
  {
    type: "category",
    label: "Open Source",
    collapsed: false,
    collapsible: false,
    items: [
      "oss/getting-started/index",
      "oss/projects",
      "oss/open-source",
      "oss/community",
      "oss/contributing",
      "oss/commitment",
      "oss/software-architecture-philosophy",
      {
        type: "category",
        label: "Guidelines",
        items: [
          "oss/guidelines/rest-api-guidelines",
          "oss/guidelines/e2e-integration-tests",
        ],
      },
      "oss/deployment",
      "oss/configuring",
      {
        type: "category",
        label: "Operations and SRE",
        items: [
          {
            type: "autogenerated",
            dirName: "self-hosted/operations",
          },
        ],
      },
      "oss/upgrading",
      "oss/sqa",
      "oss/changelog",
    ],
  },
  {
    type: "category",
    label: "Ory Kratos - Identities",
    items: ["kratos/quickstart"],
  },
  {
    type: "category",
    label: "Ory Hydra - OAuth2 & OIDC",
    items: ["hydra/self-hosted/quickstart"],
  },
  {
    type: "category",
    label: "Ory Keto - Permissions",
    items: ["keto/quickstart"],
  },
  {
    type: "category",
    label: "Ory Polis - SAML Enterprise SSO",
    items: ["polis/quickstart"],
  },
  {
    type: "category",
    label: "Ory Oathkeeper - Zero Trust Proxy",
    items: ["oathkeeper/index"],
  },
]

export default ossSidebar
