// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

const quickstartsSidebar = [
  {
    type: "doc",
    id: "getting-started/overview",
    label: "Quickstarts",
  },
  {
    type: "category",
    label: "Ory Network",
    collapsed: false,
    collapsible: false,
    items: [
      {
        type: "category",
        label: "Identity Management",
        collapsed: true,
        collapsible: true,
        items: [
          "identities/index",
          "identities/get-started/index",
          "identities/get-started/setup",
          "identities/get-started/sign-up",
          "identities/get-started/sign-in",
          "identities/get-started/sign-out",
          "identities/get-started/session-management",
          "identities/get-started/account-recovery",
          "identities/get-started/mfa",
          "identities/get-started/passwordless",
          "identities/get-started/social-sign-in",
        ],
      },
      {
        type: "category",
        label: "OAuth2 & OpenID Connect",
        collapsed: true,
        collapsible: true,
        items: [
          "oauth2-oidc/index",
          "getting-started/ory-network-oauth2",
        ],
      },
      {
        type: "category",
        label: "Integration by Language",
        collapsed: true,
        collapsible: true,
        items: [
          {
            type: "autogenerated",
            dirName: "getting-started/integrate-auth",
          },
        ],
      },
    ],
  },
      {
        type: "category",
        label: "Ory Enterprise License",
        collapsed: false,
        collapsible: false,
        items: [
          "self-hosted/oel/index",
          "self-hosted/oel/quickstart",
        ],
      },
      {
        type: "category",
        label: "Ory Open Source",
        collapsed: false,
        collapsible: false,
        items: [
          {
            type: "category",
            label: "Ory Kratos",
            collapsed: true,
            collapsible: true,
            items: [
              "identities/index",
              "kratos/quickstart",
            ],
          },
          {
            type: "category",
            label: "Ory Hydra",
            collapsed: true,
            collapsible: true,
            items: [
              "oauth2-oidc/index",
              "hydra/self-hosted/quickstart",
              {
                type: "category",
                label: "Hydra Guides",
                collapsed: true,
                collapsible: true,
                items: [
                  {
                    type: "autogenerated",
                    dirName: "hydra/guides",
                  },
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Ory Keto",
            collapsed: true,
            collapsible: true,
            items: [
              "keto/index",
              "keto/quickstart",
            ],
          },
          {
            type: "category",
            label: "Ory Polis",
            collapsed: true,
            collapsible: true,
            items: [
              "polis/index",
              "polis/quickstart",
            ],
          },
          {
            type: "category",
            label: "Ory Oathkeeper",
            collapsed: true,
            collapsible: true,
            items: [
              "oathkeeper/index",
            ],
          },
          {
            type: "category",
            label: "Integration by Language",
            collapsed: true,
            collapsible: true,
            items: [
              {
                type: "autogenerated",
                dirName: "getting-started/integrate-auth",
              },
            ],
          },
        ],
      },
]

export default quickstartsSidebar;