// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

const quickstartsSidebar = [
  {
    type: "category",
    label: "Quickstarts",
    collapsed: false,
    collapsible: false,
    link: {
      type: "doc",
      id: "getting-started/overview",
    },
    items: [
      {
        type: "autogenerated",
        dirName: "getting-started/integrate-auth",
      },
    ],
  },
]

export default quickstartsSidebar