module.exports = {
  docs: [
    {
      Introduction: [
        'welcome',
        'roots',
        'arch'
      ]
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          'Using the Ory Console': [
            {
              type: 'autogenerated',
              dirName: 'guides/console'
            },
            'concepts/terminology',
            'concepts/project',
            'concepts/project-invite-membership',
            'concepts/managed-ui',
            'concepts/identity',
            'concepts/services-api',
            'concepts/personal-access-token',
          ]
        },
        {
          'Ory CLI': [
            {
              type: 'autogenerated',
              dirName: 'guides/cli'
            }
          ]
        },
        {
          'Examples': [
            {
              type: 'autogenerated',
              dirName: 'guides/protect-page-login'
            }
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Identity Management',
      items: [
        'identity-overview',
        'kratos/concepts/identity-schema',
        {
          'Managing Identities': [
            'guides/manage-identities/managing-users-identities',
            'guides/manage-identities/import-identity',
            'guides/manage-identities/account-recovery'
          ]
        },
        {
          'Social Sign-in': [
            'guides/social-signin/overview',
            {
              'Integrating Providers': [
                'guides/social-signin/google',
                'guides/social-signin/facebook',
                'guides/social-signin/microsoft',
                'guides/social-signin/github',
                'guides/social-signin/generic',
                'guides/social-signin/apple',
                'guides/social-signin/gitlab',
                'guides/social-signin/auth0',
                'guides/social-signin/slack',
                'guides/social-signin/spotify',
                'guides/social-signin/discord',
                'guides/social-signin/twitch',
                'guides/social-signin/netid',
                'guides/social-signin/yandex',
                'guides/social-signin/vk'
                ]
              }
          ]
        }
   		]  
		}
	]
};