module.exports = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: ["welcome", "security-model"],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/local-development",
        {
          type: "category",
          label: "Integrate Authentication",
          items: [
            {
              "Server-Side App": [
                "getting-started/integrate-auth/go",
                "getting-started/integrate-auth/php",
                "getting-started/integrate-auth/expressjs",
              ],
            },
            {
              "Single Page App (SPA)": [
                "getting-started/integrate-auth/nextjs",
                "getting-started/integrate-auth/flutter-web-redirect",
                "getting-started/integrate-auth/react",
                "getting-started/integrate-auth/vue",
              ],
            },
            {
              "Native App": ["getting-started/integrate-auth/react-native"],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "doc",
        id: "guides/index",
      },
      items: [
        {
          type: "category",
          label: "Ory CLI",
          items: [
            {
              type: "autogenerated",
              dirName: "guides/cli",
            },
            {
              Reference: [
                {
                  type: "autogenerated",
                  dirName: "cli",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Passwordless",
          items: ["guides/passwordless/webauthn"],
        },
        {
          type: "category",
          label: "Managing Sessions",
          items: [
            "guides/session-management/overview",
            "guides/session-management/session-management",
            "guides/session-management/session-lifespan",
            "guides/session-management/check-session",
            "guides/session-management/refresh-extend-sessions",
          ],
        },
        {
          type: "category",
          label: "Managing Identities",
          items: [
            {
              type: "autogenerated",
              dirName: "guides/manage-identities",
            },
          ],
        },
        {
          type: "category",
          label: "Permissions",
          items: ["guides/permissions/overview"],
        },
        {
          type: "category",
          label: "Social Sign-in",
          items: [
            "guides/social-signin/overview",
            {
              "Integrating Providers": [
                "guides/social-signin/generic",
                "guides/social-signin/google",
                "guides/social-signin/facebook",
                "guides/social-signin/microsoft",
                "guides/social-signin/github",
                "guides/social-signin/apple",
                "guides/social-signin/gitlab",
                "guides/social-signin/auth0",
                "guides/social-signin/slack",
                "guides/social-signin/spotify",
                "guides/social-signin/discord",
                "guides/social-signin/twitch",
                "guides/social-signin/netid",
                "guides/social-signin/yandex",
                "guides/social-signin/vk",
                "guides/social-signin/dingtalk",
              ],
            },
            "guides/social-signin/get-tokens",
            "guides/social-signin/data-mapping",
          ],
        },
        {
          type: "category",
          label: "Multi-Factor Authentication (MFA)",
          items: [
            {
              type: "autogenerated",
              dirName: "guides/mfa",
            },
          ],
        },
        "guides/emails",
        {
          type: "category",
          label: "Customizing Ory",
          items: ["guides/custom-domains", "guides/bring-your-user-interface"],
        },
      ],
    },
    {
      Concepts: [
        "concepts/terminology",
        "concepts/project",
        "concepts/redirects",
        "concepts/personal-access-token",
        "ecosystem/api-design",
        "concepts/password-policy",
      ],
    },
    {
      type: "category",
      label: "Identity Management (Ory Kratos)",
      items: [
        {
          Introduction: [
            "kratos/index",
            "kratos/quickstart",
            "kratos/install",
            "kratos/configuring",
          ],
        },
        {
          Concepts: [
            "kratos/concepts/index",
            "kratos/concepts/ui-user-interface",
            "kratos/concepts/browser-redirect-flow-completion",
            "kratos/concepts/email-sms",
            "kratos/concepts/security",
            {
              label: "Identity Credentials",
              type: "category",
              items: [
                "kratos/concepts/credentials",
                "kratos/concepts/credentials/username-email-password",
              ],
            },
          ],
        },
        {
          "Self Service (End-User)": [
            "kratos/self-service",
            "kratos/self-service/flows/user-registration",
            "kratos/self-service/flows/user-login",
            "kratos/self-service/flows/user-settings",
            "kratos/self-service/flows/account-recovery",
            "kratos/self-service/flows/verify-email-account-activation",
            "kratos/self-service/flows/user-logout",
            "kratos/self-service/flows/user-facing-errors",
            "kratos/self-service/hooks",
          ],
        },
        {
          Guides: [
            "kratos/guides/configuring-cookies",
            "kratos/guides/deploy-kratos-example",
            "kratos/guides/multi-domain-cookies",
            "kratos/guides/setting-up-cors",
            "kratos/guides/password-policy",
            "kratos/guides/account-recovery-password-reset",
            "kratos/guides/account-activation-email-verification",
            "kratos/guides/zero-trust-iap-proxy-identity-access-proxy",
            "kratos/guides/multi-tenancy-multitenant",
            "kratos/guides/secret-key-rotation",
            "kratos/guides/select-cipher-algorithm",
            "kratos/guides/high-availability-ha",
            "kratos/guides/docker",
            "kratos/guides/https-tls",
            "kratos/guides/setting-up-password-hashing-parameters",
            "kratos/guides/integration-with-other-systems-using-web-hooks",
            "kratos/guides/tracing",
            "kratos/guides/upgrade",
          ],
        },
        "kratos/reference/api",
        {
          Reference: [
            "kratos/reference/configuration",
            "kratos/reference/configuration-editor",
            "kratos/reference/json-schema-json-paths",
            "kratos/reference/html-forms",
            "kratos/reference/jsonnet",
            {
              "Command Line Interface (CLI)": [
                {
                  type: "autogenerated",
                  dirName: "kratos/cli",
                },
              ],
            },
          ],
        },
        {
          SDKs: ["kratos/sdk/index", "kratos/sdk/go"],
        },
        {
          "Debug & Help": [
            "kratos/debug/troubleshooting",
            "kratos/debug/csrf",
            "kratos/debug/performance-out-of-memory-password-hashing-argon2",
            "kratos/debug/debug-docker-delve-ory-kratos",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "OAuth2 & OpenID Connect (Ory Hydra)",
      items: [
        {
          Introduction: ["hydra/index", "hydra/5min-tutorial", "hydra/install"],
        },
        {
          Concepts: [
            "hydra/concepts/before-oauth2",
            "hydra/concepts/oauth2",
            "hydra/concepts/openid-connect-oidc",
            "hydra/concepts/login",
            "hydra/concepts/consent",
            "hydra/concepts/logout",
            "hydra/jwks",
            "hydra/limitations",
          ],
        },
        {
          Guides: [
            {
              type: "category",
              label: "Implementing the User Interface",
              items: [
                "hydra/guides/login",
                "hydra/guides/consent",
                "hydra/guides/logout",
              ],
            },
            {
              type: "category",
              label: "Operations",
              items: [
                "hydra/configure-deploy",
                "hydra/dependencies-environment",
                "hydra/production",
                "hydra/guides/deploy-hydra-example",
                "hydra/guides/tracing",
                "hydra/guides/hsm-support",
                "hydra/guides/secrets-key-rotation",
                "hydra/guides/kubernetes-helm-chart",
                "hydra/guides/ssl-https-tls",
                "hydra/guides/cookies",
                "hydra/guides/scaling-hydra",
                "hydra/guides/cors",
                "hydra/guides/gitlab",
                "hydra/guides/migrating-from-mitreid",
                "hydra/guides/merge-multiple-db-secrets",
                "hydra/guides/upgrade",
              ],
            },
            {
              type: "category",
              label: "OAuth2 & OpenID Connect",
              items: [
                "hydra/advanced",
                "hydra/guides/openid-connect-dynamic-client-registration",
                "hydra/guides/oauth2-clients",
                "hydra/guides/oauth2-grant-type-jwt-bearer",
                "hydra/guides/common-oauth2-openid-connect-flows",
                "hydra/guides/using-oauth2",
                "hydra/guides/client-token-expiration",
                "hydra/guides/oauth2-token-introspection",
                "hydra/guides/oauth2-public-spa-mobile",
                "hydra/guides/claims-at-refresh",
              ],
            },
          ],
        },
        "hydra/reference/api",
        {
          Reference: [
            "hydra/reference/configuration",
            "hydra/reference/configuration-editor",
            {
              "Command Line Interface (CLI)": [
                {
                  type: "autogenerated",
                  dirName: "hydra/cli",
                },
              ],
            },
          ],
        },
        {
          "Debug & Help": [
            "hydra/debug",
            "hydra/debug/csrf",
            "hydra/debug/config",
            "hydra/debug/token-endpoint-auth-method",
            "hydra/debug/logout",
            "hydra/faq",
          ],
        },
        {
          SDKs: ["hydra/sdk", "hydra/sdk/go", "hydra/sdk/js", "hydra/sdk/php"],
        },
        {
          "Further Reading": [
            "hydra/case-study",
            "hydra/benchmark",
            "hydra/security-architecture",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Permissions & Access Control (Ory Keto)",
      items: [
        {
          Introduction: [
            "keto/index",
            "keto/install",
            "keto/performance",
            "keto/quickstart",
          ],
        },
        {
          Concepts: [
            "keto/concepts/relation-tuples",
            "keto/concepts/namespaces",
            "keto/concepts/objects",
            "keto/concepts/subjects",
            "keto/concepts/graph-of-relations",
            "keto/concepts/api-overview",
            "keto/concepts/internal-algorithms",
            "keto/concepts/snaptokens-evaluation-consistency",
          ],
        },
        {
          Guides: [
            "keto/secure",
            "keto/guides/simple-access-check-guide",
            "keto/guides/list-api-display-objects",
            "keto/guides/expand-api-display-who-has-access",
            "keto/guides/production",
            "keto/guides/v0.7-migration",
            "keto/guides/migrating-legacy-policies",
            "keto/guides/rbac",
            "keto/guides/access-control-inheritance",
            "keto/guides/access-control-list-design-best-practices",
            "keto/guides/upgrade",
          ],
        },
        {
          Examples: ["keto/examples/olymp-file-sharing"],
        },
        {
          Reference: [
            "keto/reference/configuration",
            "keto/reference/configuration-editor",
            "keto/reference/rest-api",
            "keto/reference/proto-api",
            {
              "Command Line Interface (CLI)": [
                {
                  type: "autogenerated",
                  dirName: "keto/cli",
                },
              ],
            },
          ],
        },
        {
          SDKs: ["keto/sdk/index", "keto/sdk/go"],
        },
      ],
    },
    {
      type: "category",
      label: "Zero Trust Proxy (Ory Oathkeeper)",
      items: [
        {
          Introduction: ["oathkeeper/index", "oathkeeper/install"],
        },
        {
          "Core Concepts": [
            "oathkeeper/api-access-rules",
            {
              type: "category",
              label: "Handlers",
              items: [
                "oathkeeper/pipeline",
                "oathkeeper/pipeline/authn",
                "oathkeeper/pipeline/authz",
                "oathkeeper/pipeline/mutator",
                "oathkeeper/pipeline/error",
              ],
            },
          ],
        },
        {
          Guides: [
            "oathkeeper/configure-deploy",
            "oathkeeper/guides/proxy-websockets",
            "oathkeeper/guides/traefik-proxy-integration",
            "oathkeeper/guides/upgrade",
          ],
        },
        "oathkeeper/reference/api",
        {
          Reference: [
            "oathkeeper/reference/configuration",
            "oathkeeper/reference/configuration-editor",
            {
              "Command Line Interface (CLI)": [
                {
                  type: "autogenerated",
                  dirName: "oathkeeper/cli",
                },
              ],
            },
          ],
        },
        {
          SDKs: ["oathkeeper/sdk"],
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: ["reference/api"],
    },
  ],
  opensource: [
    "open-source",
    "ecosystem/contributing",
    "ecosystem/community",
    "ecosystem/projects",
    "ecosystem/security",
    "ecosystem/roadmap",
    "ecosystem/changelog",
    "ecosystem/versioning",
    "ecosystem/configuring",
    "ecosystem/deployment",
    "ecosystem/upgrading",
    "ecosystem/logging",
    "ecosystem/sqa",
    "ecosystem/software-architecture-philosophy",
  ],
}
