module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Protect a Page or Screen with Login',
          link: {
            type: 'doc',
            id: 'next/guides/protect-page-login'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'next/guides/protect-page-login'
            }
          ]
        },
        {
          type: 'category',
          label: 'Set Up Multi-Factor Authentication',
          link: {
            type: 'doc',
            id: 'next/guides/set-up-mfa'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'next/guides/set-up-mfa'
            }
          ]
        },
        {
          type: 'category',
          label: 'Using the Ory Console',
          items: [
            {
              type: 'autogenerated',
              dirName: 'next/guides/console'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Self-Hosting Ory Components',
      items: [
        {
          type: 'category',
          label: 'Ory Identity (Ory Kratos)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'next/self-hosted/identity'
            }
          ]
        }
      ]
    },
    {
      LEGACY: [
        'get-started',
        {
          'Ory Cloud': [
            {
              'Start Building': [
                'start-building',
                'start-building/ory-cli-install-use',
                'start-building/server-side-web-app',
                'start-building/single-page-app-spa',
                'start-building/native-mobile-app',
                'start-building/deploy-auth-production',
                'start-building/other-languages'
              ]
            },
            {
              Guides: [
                'guides/proxy',
                'guides/custom-domains',
                'guides/bring-your-user-interface',
                'guides/create-personal-access-token',
                'guides/customize-identity-schema'
              ]
            },
            {
              Concepts: [
                'concepts/terminology',
                'concepts/project',
                'concepts/project-invite-membership',
                'concepts/managed-ui',
                'concepts/identity',
                'concepts/services-api',
                'concepts/personal-access-token',
                'concepts/self-service',
                'concepts/redirects',
                'concepts/session',
                'concepts/emails',
                'ecosystem/api-design',
                'concepts/password-policy'
              ]
            },
            'reference/api',
            {
              Reference: [
                {
                  'Command Line Interface (CLI)': [
                    'cli/ory',
                    'cli/ory-proxy',
                    'cli/ory-version'
                  ]
                }
              ]
            },
            {
              Debug: ['debug/smtp-courier-1']
            },
            'cloud/developer',
            'cloud/cloud-roadmap'
          ]
        },
        {
          'Open Source Overview': [
            'open-source',
            'ecosystem/community',
            'ecosystem/projects',
            'ecosystem/versioning',
            'ecosystem/configuring',
            'ecosystem/deployment',
            'ecosystem/upgrading',
            'ecosystem/logging',
            'ecosystem/contributing',
            'ecosystem/sqa',
            'ecosystem/security',
            'ecosystem/roadmap',
            'ecosystem/software-architecture-philosophy'
          ]
        }
      ]
    }
  ]
}
